### ISSUE TITLE
Install bug - null reference exception

### ISSUE THREAD

**Issue by Kurren123** [Microsoft/VS-PPT#109]
Hi

I'm trying to install the Ctrl+Click Go To Definition extension to VS 2017, having no other PPT extensions installed. The installation fails with the following log (see below). Is it maybe possible to install the PPT options page separately?

```
21.3.17 09:17:40 - Microsoft VSIX Installer
21.3.17 09:17:40 - -------------------------------------------
21.3.17 09:17:40 - vsixinstaller.exe version:
21.3.17 09:17:40 - 15.0.26020.0 built by: D15REL
21.3.17 09:17:40 - -------------------------------------------
21.3.17 09:17:40 - Command line parameters:
21.3.17 09:17:40 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe,/skuName:Enterprise,/skuVersion:15.0.26020.0,/appidname:Microsoft Visual Studio Enterprise 2017 RC,C:\Users\Kurren.Nischal\AppData\Local\Temp\VSIX1sqwstwa.vsix
21.3.17 09:17:40 - -------------------------------------------
21.3.17 09:17:40 - Microsoft VSIX Installer
21.3.17 09:17:40 - -------------------------------------------
21.3.17 09:17:41 - Initializing Install...
21.3.17 09:17:41 - Extension Details...
21.3.17 09:17:41 - 	Identifier         : CtrlClickGoToDefn.b66d9c08-a6c6-4fbf-9827-ba4693968419
21.3.17 09:17:41 - 	Name               : Ctrl+Click Go To Definition
21.3.17 09:17:41 - 	Author             : Microsoft
21.3.17 09:17:41 - 	Version            : 15.0.2
21.3.17 09:17:41 - 	Description        : Make ctrl+click perform a "Go To Definition" on the identifier under the cursor.
Also, when the ctrl key is held down, highlight identifiers that look like they have definitions to navigate to.
21.3.17 09:17:41 - 	Locale             : en-US
21.3.17 09:17:41 - 	MoreInfoURL        : https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.CtrlClickGoToDefinition
21.3.17 09:17:41 - 	InstalledByMSI     : False
21.3.17 09:17:41 - 	SupportedFrameworkVersionRange : [4.5,)
21.3.17 09:17:41 - 
21.3.17 09:17:42 - 	SignatureState     : ValidSignature
21.3.17 09:17:42 - 	SignedBy           : Microsoft Corporation
21.3.17 09:17:42 - 	Certificate Info   : 
21.3.17 09:17:42 - 		-------------------------------------------------------
21.3.17 09:17:42 - 		[Subject]       : CN=Microsoft Corporation, OU=MOPR, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
21.3.17 09:17:42 - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
21.3.17 09:17:42 - 		[Serial Number] : 33000000FF6B54F91DD1781A1C0000000000FF
21.3.17 09:17:42 - 		[Not Before]    : 12.2.16 01:12:29
21.3.17 09:17:42 - 		[Not After]     : 12.5.17 02:12:29
21.3.17 09:17:42 - 		[Thumbprint]    : 6F1691367DB1D2F6278B8A82A1C4095D3BC0AF1C
21.3.17 09:17:42 - 
21.3.17 09:17:42 - 	Supported Products : 
21.3.17 09:17:42 - 		Microsoft.VisualStudio.Community
21.3.17 09:17:42 - 			Version : [15.0]
21.3.17 09:17:42 - 
21.3.17 09:17:42 - 	References         : 
21.3.17 09:17:42 - 		-------------------------------------------------------
21.3.17 09:17:42 - 		Identifier   : PPTOptionsPage.666715a6-3ac4-4bb7-b538-4d7625f99666
21.3.17 09:17:42 - 		Name         : Productivity Power Tools Options Page
21.3.17 09:17:42 - 		Version      : [2.0,16.0)
21.3.17 09:17:42 - 		MoreInfoURL  : 
21.3.17 09:17:42 - 		Nested       : Yes
21.3.17 09:17:42 - 
21.3.17 09:17:42 - 	Prerequisites      : 
21.3.17 09:17:42 - 		-------------------------------------------------------
21.3.17 09:17:42 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
21.3.17 09:17:42 - 		Name         : Visual Studio core editor
21.3.17 09:17:42 - 		Version      : [15.0.25904.2,16.0)
21.3.17 09:17:42 - 
21.3.17 09:17:42 - Signature Details...
21.3.17 09:17:42 - 	Extension is signed with a valid signature.
21.3.17 09:17:42 - 
21.3.17 09:17:44 - The extension with ID 'CtrlClickGoToDefn.b66d9c08-a6c6-4fbf-9827-ba4693968419' is not installed to Microsoft Visual Studio Enterprise 2017 RC.
21.3.17 09:18:47 - The following target products have been selected...
21.3.17 09:18:47 - 	Microsoft Visual Studio Enterprise 2017 RC
21.3.17 09:18:47 - 
21.3.17 09:18:49 - Beginning to install extension to Microsoft Visual Studio Enterprise 2017 RC...
21.3.17 09:18:49 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 doesn't declare a chip
21.3.17 09:18:49 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:49 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:49 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:49 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:49 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:49 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:49 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:49 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:49 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:49 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:49 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:49 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:49 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:49 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:49 - Dependency Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 doesn't declare a chip
21.3.17 09:18:50 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 doesn't declare a chip
21.3.17 09:18:50 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:50 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:50 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:50 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:50 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:50 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:50 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:50 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:50 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:50 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:50 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:50 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:50 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:50 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
21.3.17 09:18:50 - Dependency Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 doesn't declare a chip
21.3.17 09:18:50 - Install Error : Microsoft.VisualStudio.ExtensionManager.NestedExtensionInstallException: The extension 'PPTOptionsPage.666715a6-3ac4-4bb7-b538-4d7625f99666' nested within 'CtrlClickGoToDefn.b66d9c08-a6c6-4fbf-9827-ba4693968419' failed to install.
Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.RefreshExtractedPackageStream(IInstalledExtension parentExtension, IExtensionReference reference)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallNestedExtensions(InstallableExtensionImpl parentExtension, IInstalledExtension installedParentExtension, ZipPackage parentVSIX, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallNestedExtensions(InstallableExtensionImpl parentExtension, IInstalledExtension installedParentExtension, ZipPackage parentVSIX, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformLegacyInstall(InstallableExtensionImpl extension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Boolean isPackComponent, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

```

**Comment by Kurren123** [comment]
Didn't realize I had vs2017 RC installed. For anyone reading this, upgrading to vs2017 did the trick. Please close :)
