### ISSUE TITLE
The 'OptionsPagePackage' package did not load correctly - 2

### ISSUE THREAD

**Issue by franzalex** [Microsoft/VS-PPT#124]
Possibly related to #122 

With the latest version of PPT (v15.0.2) installed on VS 2017 Community version 15.1 (26403.0), a message box appears shortly after VS has loaded stating that the OptionsPagePackage failed to load correctly.

The following is the description of the entry in the [`ActivityLog.xml`](https://github.com/Microsoft/VS-PPT/files/925269/ActivityLog.xml.txt "Portion of ActivityLog.xml file with the entry being described") file:

```
CreateInstance failed for package [OptionsPagePackage]Source: 'mscorlib' Description: Could not load file or assembly 'file:///C:\USERS\USER\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_D178CF2C\EXTENSIONS\5jyc2maa.rrx\PPTOptionsPage.dll' or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\USERS\USER\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_D178CF2C\EXTENSIONS\5jyc2maa.rrx\PPTOptionsPage.dll' or one of its dependencies. The system cannot find the file specified.
File name: 'file:///C:\USERS\USER\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_D178CF2C\EXTENSIONS\5jyc2maa.rrx\PPTOptionsPage.dll'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

Since this error seems to be due to the fact that the **PPT Options Page** component is not installed, I attempted to install it manually. However, following the [PPT Options Page hyperlink][1] in the repository's [Readme.md][GitHub-VS-PPT] yielded the following "Page not found" result:

![PPT Options Page on marketplace.visualstudio.com](https://cloud.githubusercontent.com/assets/7560066/25085420/a49b6bb0-2351-11e7-9ccf-dac25d5b6776.png)

Interestingly, once the main Productivity Power Tools extension is disabled in VS, this error stops showing up with no apparent adverse effect on the options page or elsewhere.

 [1]: https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProductivityPowerToolsOptionsPage "PPT Options Page"
 [GitHub-VS-PPT]: https://github.com/Microsoft/VS-PPT/blob/44b565e/README.md

**Attached Files:**

 * [ActivityLog.xml](https://github.com/Microsoft/VS-PPT/files/925269/ActivityLog.xml.txt)

**Comment by justcla** [comment]
The PPT Installer did not change. Only the extensions that get installed by the installer changed.
For best results, try completely uninstalling all PPT extensions, then reinstall them.
If there are old or mismatched versions of the extensions, you might get strange results.
The only extensions that use the PPTOptionsPage are:
- Ctrl+Click GoToDefn
- Match Margin
- Shrink Empty Lines
- Time Stamp Margin

So make sure they are all up to date with the latest versions.

**Comment by franzalex** [comment]
You're right. The error ceased to appear after ensuring that the four extensions you listed had been updated to the latest version.

It's possible that an incomplete automatic update caused this bug to start with.
Could there be a more graceful way of trapping this exception in future?

**Comment by justcla** [comment]
Glad you got it fixed. Thanks for reporting back.

I'm not sure about trapping this exception in future.
We might need to see why the auto-update didn't remove the old extensions.

**Comment by franzalex** [comment]
That's alright.

Your attention has at least been drawn to this potential bug so I hope there'll be a workaround soon.
Also, having this error documented means that others who get a similar error in future will know the likely cause and how to solve it.

**Comment by justcla** [comment]
@franzalex There is no workaround. It was just some bad extensions that have now been fixed. The only problem was users who had trouble removing/updating the old extensions. The fix is to update all the bad extensions.
