### ISSUE TITLE
MatchMargin Does not install on 15.8.7, 15.8.8 and 15.9.0preview

### ISSUE THREAD

**Issue by ujaf** [Microsoft/VS-PPT#210]

**Comment by prnadago** [comment]
Hey @ujaf , we're not able to repro this ourselves, have you tried installing it individually through the Extensions and Updates dialog instead of through the Productivity Power Tools extension pack? Where do you hit an error?

The best way for us to find a fix is to get logs from you through the 'Report a Problem' tool in VS. It would be great if you could please follow the instructions on https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017, especially "Record a Repro" section to provide a trace and heap dump and share with us.

We'll follow up from there. Thanks!

**Comment by ujaf** [comment]
Hi Pratik,

Thanks for your quick reply!

I attach the log and details of VS2017 installation – relevant part seems:
26/10/2018 10:06:04 -     Supported Products :
26/10/2018 10:06:04 -                     Microsoft.VisualStudio.Community
26/10/2018 10:06:04 -                                     Version : [15.0,17.0)
26/10/2018 10:06:04 -
26/10/2018 10:06:04 -     References      :
26/10/2018 10:06:04 -                     -------------------------------------------------------
26/10/2018 10:06:04 -                     Identifier   : PPTOptionsPage.666715a6-3ac4-4bb7-b538-4d7625f99666
26/10/2018 10:06:04 -                     Name         : Productivity Power Tools Options Page
26/10/2018 10:06:04 -                     Version      : [2.0,17.0)
26/10/2018 10:06:04 -                     MoreInfoURL  :
26/10/2018 10:06:04 -                     Nested       : Yes
26/10/2018 10:06:04 -
26/10/2018 10:06:04 -
26/10/2018 10:06:04 - Searching for applicable products...
26/10/2018 10:06:04 - Found installed product - Microsoft Visual Studio Professional 2012
26/10/2018 10:06:04 - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
26/10/2018 10:06:04 - Found installed product - Global Location
26/10/2018 10:06:04 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

I do have visual studio 2017 15.8.8 installed, and have also tried with 15.8.7 and with 15.9 preview – it worked with previous versions of VS2017, I cannot say exactly until which revision.
I tried installing both from the separate installer and from the PPT installer, and both from within VS and from the separate installer – all give the same results.

Thanks and best regards,
Uri

[cid:image001.png@01D46D14.4E148C50]
