### ISSUE TITLE
System.InvalidOperationException occurring in StructureVizualizer

### ISSUE THREAD

**Issue by justcla** [Microsoft/VS-PPT#43]
Notes from Martin Lemburg:

Sorry, but there is a seldom occuring exception in the StructureVisualizer:

System.InvalidOperationException:
	Stack empty.
		at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
		at System.Collections.Generic.Stack`1.Pop()
		at Microsoft.PowerToolsEx.BlockTagger.Implementation.CodeBlock.Context(BlockColoring coloring, TextRunProperties properties)
		at Microsoft.VisualStudio.PowerTools.StructureVisualizer.StructureAdornmentManager.PreprocessMouseMove(MouseEventArgs e)
		at Microsoft.VisualStudio.Text.Utilities.WpfMouseProcessor.<>c__DisplayClass37_0.<UIElement_MouseMove>b__0(IMouseProcessor p)
		at Microsoft.VisualStudio.Text.Utilities.WpfMouseProcessor.<>c__DisplayClass56_1.<MouseProcessorHandler>b__0()
		at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)

**Comment by MartinL0815** [comment]
Thanks for creating the issue from my VSGallery discussioN!
