### ISSUE TITLE
Unable to install any 2017 PPT extensions: NoApplicableSKUsException

### ISSUE THREAD

**Issue by grantbowering** [Microsoft/VS-PPT#78]
I tried to install 6 different PPT extensions this morning and all of them claimed I didn't have Visual Studio 2017 installed.

```
2017-01-18 11:37:44 AM - 
2017-01-18 11:37:44 AM - 	Supported Products : 
2017-01-18 11:37:44 AM - 		Microsoft.VisualStudio.Community
2017-01-18 11:37:44 AM - 			Version : [15.0]
2017-01-18 11:37:44 AM - 
2017-01-18 11:37:44 AM - 	References         : 
2017-01-18 11:37:44 AM - 		-------------------------------------------------------
2017-01-18 11:37:44 AM - 		Identifier   : Microsoft.VisualStudio.MPF.12.0
2017-01-18 11:37:44 AM - 		Name         : Visual Studio MPF 12.0
2017-01-18 11:37:44 AM - 		Version      : [12.0]
2017-01-18 11:37:44 AM - 		MoreInfoURL  : 
2017-01-18 11:37:44 AM - 		Nested       : No
2017-01-18 11:37:44 AM - 
2017-01-18 11:37:44 AM - Signature Details...
2017-01-18 11:37:44 AM - 	Extension is signed with a valid signature.
2017-01-18 11:37:44 AM - 
2017-01-18 11:37:44 AM - Searching for applicable products...
2017-01-18 11:37:44 AM - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
2017-01-18 11:37:44 AM - Found installed product - Microsoft Visual Studio Enterprise 2015
2017-01-18 11:37:44 AM - Found installed product - Microsoft Visual Studio Professional 2015
2017-01-18 11:37:44 AM - Found installed product - Microsoft Visual Studio Community 2015
2017-01-18 11:37:44 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
2017-01-18 11:37:44 AM - Found installed product - Global Location
2017-01-18 11:37:44 AM - Found installed product - ssms
2017-01-18 11:37:44 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

Yet I clearly do have it installed, I'm using it daily.  It's right here on my Programs and Features list:
![image](https://cloud.githubusercontent.com/assets/2152220/22077988/aadea9ac-dd73-11e6-91e0-8c36f0b382e8.png)

Any advice?

**Comment by grantbowering** [comment]
(Also interesting is that in Programs and Features it says 1.0.21110.1, but in the 2017 About dialog it says 15.0.26020.0.  Thought the major build numbers might match but I guess it doesn't update programs and features when it updates...  I don't think it's a version mismatch issue though, given that nothing about 2017 appears in the search results list in the install logs at all...)

**Comment by grantbowering** [comment]
Found [this issue](https://github.com/JosefPihrt/Roslynator/issues/22) for an extension that seemed to be experiencing the same phenomenon.  Looks like it was closed due to lack of feedback, not because the issue was resolved; I tried and can't install that one either.

**Comment by grantbowering** [comment]
There's no "Repair" operation for VS 2017, but I grabbed the installer again, hit "Modify", turned on an extra option, and that seemed to do the same thing...  
I got an installer failure, that vs.emulator.android.bundle failed to install due to "Unknown error (0x80044000)".  So I unchecked the "Visual Studio Emulator for Android" option under Emulators and hit Modify again, and it immediately completed, and now 3 out of 6 PPT extensions installed!  (The other 3 are the same PPTOptionsPage error everyone's getting)
Closed :)
